# Site settings
# These are used to personalize your new site. You can access them via {{ site.title }}, {{ site.email }}, etc.

title: "TechCognita | Blogs"
email: "shindeatharv576@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the TechCognita Blog! Explore the latest technology insights, tutorials, and updates.
baseurl: "/TechCognita_Blog" # If you're hosting on a subpath, like 'username.github.io/repo_name'
url: "https://atharvshinde2004.github.io" # Replace with your GitHub username and repository name
twitter_username: "yourtwitterusername"  # Replace with your Twitter handle
github_username: "yourgithubusername"  # Replace with your GitHub username

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude files that you don't want to be processed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Author and other meta information
author: "Atharv Shinde"  # Your name

# Optional: Pagination settings
paginate: 5  # Number of posts to show per page
paginate_path: "/page:num"  # Pagination path format

# Markdown settings (optional, depends on your preferred markdown processor)
markdown: kramdown

# Social Media and Analytics (Optional)
# Add your social media links and analytics tracking (like Google Analytics) below:

social:
  - name: "twitter"
    url: "https://twitter.com/yourtwitterhandle"  # Replace with your Twitter handle
  - name: "github"
    url: "https://github.com/yourgithubusername"  # Replace with your GitHub profile URL
  - name: "linkedin"
    url: "https://www.linkedin.com/in/yourlinkedinprofile"  # Replace with your LinkedIn profile URL

# Google Analytics or other tracking code (optional)
google_analytics: "UA-XXXXX-Y"  # Replace with your Google Analytics tracking ID
